openduty/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from rest_framework import routers as rest_routers
from openduty import views
from . import incidents, healthcheck
from django.contrib import admin
from schedule.periods import  Month, Week

admin.autodiscover()
rest_router = rest_routers.SimpleRouter(trailing_slash=False)
rest_router.register(r'users', views.UserViewSet)
rest_router.register(r'groups', views.GroupViewSet)
rest_router.register(r'schedule_policies', views.SchedulePolicyViewSet)
rest_router.register(r'schedule_policy_rules', views.SchedulePolicyRuleViewSet)
rest_router.register(r'create_event', incidents.IncidentViewSet)
rest_router.register(r'healthcheck', healthcheck.HealthCheckViewSet)
rest_router.register(r'celeryhealthcheck', healthcheck.CeleryHealthCheckViewSet)



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browseable API.
urlpatterns = patterns('',
    url(r'^api/', include(rest_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', 'rest_framework.authtoken.views.obtain_auth_token'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^schedule/', include('schedule.urls')),

    #AUTH
    url(r'^login/$', 'openduty.auth.login'),
    url(r'^login/do$', 'openduty.auth.do'),
    url(r'^logout/$', 'openduty.auth.logout'),

    #USERS
    url(r'^users/$', 'openduty.users.list'),
    url(r'^users/new$', 'openduty.users.new'),
    url(r'^users/save', 'openduty.users.save'),
    url(r'^users/testnotification', 'openduty.users.testnotification'),
    url(r'^users/edit/(\d+)$', 'openduty.users.edit'),
    url(r'^users/delete/(\d+)$', 'openduty.users.delete'),

    #SERVICES
    url(r'^services/$', 'openduty.services.list'),
    url(r'^services/new$', 'openduty.services.new'),
    url(r'^services/save', 'openduty.services.save'),
    url(r'^services/edit/(.*)$', 'openduty.services.edit'),
    url(r'^services/delete/(.*)$', 'openduty.services.delete'),
    url(r'^services/silence/(.*)$', 'openduty.services.silence'),

    #Policies
    url(r'^policies/$', 'openduty.escalation.list'),
    url(r'^policies/new$', 'openduty.escalation.new'),
    url(r'^policies/save', 'openduty.escalation.save'),
    url(r'^policies/edit/(.*)$', 'openduty.escalation.edit'),
    url(r'^policies/delete/(.*)$', 'openduty.escalation.delete'),


    #SCHEDULES
    url(r'^schedules/$', 'openduty.schedules.list'),
    url(r'^schedules/new$', 'openduty.schedules.new'),
    url(r'^schedules/save', 'openduty.schedules.save'),
    url(r'^schedules/edit/(\d)$', 'openduty.schedules.edit'),
    url(r'^schedules/delete/(\d)$', 'openduty.schedules.delete'),
    url(r'^schedules/view/(.*)$', 'openduty.schedules.details',   kwargs={'periods': [Month]}),

    #EVENT
    url(r'^events/create/(?P<calendar_slug>[-\w]+)/$', 'openduty.events.create_or_edit_event', name='calendar_create_event'),
    url(r'^events/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$', 'openduty.events.create_or_edit_event', name='edit_event'),
    url(r'^events/destroy/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$', 'openduty.events.destroy_event', name='destroy_event'),



    #SERVICES/API TOKEN
    url(r'^services/token_delete/(.*)$', 'openduty.services.token_delete'),
    url(r'^services/token_create/(.*)$', 'openduty.services.token_create'),

    #EVENT_LOG
    url(r'^$', 'openduty.event_log.list'),
    url(r'^dashboard/$', 'openduty.event_log.list'),
    url(r'^dashboard/service/(.*)$', 'openduty.event_log.get'),

    #INCIDENTS
    url(r'^incidents/unhandled/on-call/$', 'openduty.incidents.unhandled_for_on_call_user'),
    url(r'^incidents/unhandled/on-call/(.*)$', 'openduty.incidents.unhandled_for_on_call_user'),
    url(r'^incidents/unhandled/$', 'openduty.incidents.unhandled'),
    url(r'^incidents/unhandled/(.*)$', 'openduty.incidents.unhandled'),
    url(r'^incidents/acknowledged/$', 'openduty.incidents.acknowledged'),
    url(r'^incidents/acknowledged/(.*)$', 'openduty.incidents.acknowledged'),
    url(r'^incidents/details/(.*)$', 'openduty.incidents.details'),
    url(r'^incidents/update_type$', 'openduty.incidents.update_type'),
    url(r'^incidents/forward_incident', 'openduty.incidents.forward_incident'),
    url(r'^incidents/service/$', 'openduty.incidents.list'),
    url(r'^incidents/service/(.*)$', 'openduty.incidents.list'),
    url(r'^incidents/silence/(.*)$', 'openduty.incidents.silence'),



)

urlpatterns += patterns('',
        (r'^static/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
    )

urlpatterns += patterns('',
             (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':True}),
        )

openduty/models.py
__author__ = 'deathowl'

import uuid
import hmac
from hashlib import sha1

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from uuidfield import UUIDField
from django.core.exceptions import ValidationError
from schedule.models import Calendar
from django.contrib.auth import models as auth_models
from django.contrib.auth.management import create_superuser
from django.db.models import signals
from django.conf import settings


AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

@python_2_unicode_compatible
class Token(models.Model):
    """
    The default authorization token model.
    """
    key = models.CharField(max_length=40, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super(Token, self).save(*args, **kwargs)

    def generate_key(self):
        unique = uuid.uuid4()
        return hmac.new(unique.bytes, digestmod=sha1).hexdigest()

    def __unicode__(self):
        return self.key

    def __str__(self):
        return self.key


@python_2_unicode_compatible
class SchedulePolicy(models.Model):
    """
    Schedule policy
    """
    name = models.CharField(max_length=80, unique=True)
    repeat_times = models.IntegerField()

    class Meta:
        verbose_name = _('schedule_policy')
        verbose_name_plural = _('schedule_policies')

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.name)


@python_2_unicode_compatible
class Service(models.Model):
    """
    Incidents are representations of a malfunction in the system.
    """
    name = models.CharField(max_length=80, unique=True)
    id = UUIDField(primary_key=True, auto=True)
    retry = models.IntegerField(blank=True, null=True)
    policy = models.ForeignKey(SchedulePolicy, blank=True, null=True)
    escalate_after = models.IntegerField(blank=True, null=True)
    notifications_disabled = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('service')
        verbose_name_plural = _('service')

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.id)

@python_2_unicode_compatible
class EventLog(models.Model):
    """
    Event Log
    """
    service_key = models.ForeignKey(Service)
    data = models.TextField()
    occurred_at = models.DateTimeField()
    class Meta:
        verbose_name = _('eventlog')
        verbose_name_plural = _('eventlog')

    def __str__(self):
        return self.data

    def natural_key(self):
        return (self.service_key, self.id)


@python_2_unicode_compatible
class Incident(models.Model):
    TRIGGER = "trigger"
    RESOLVE = "resolve"
    ACKNOWLEDGE = "acknowledge"
    """
    Incidents are representations of a malfunction in the system.
    """
    service_key = models.ForeignKey(Service)
    incident_key = models.CharField(max_length=200)
    event_type = models.CharField(max_length=15)
    description = models.CharField(max_length=200)
    details = models.TextField()
    occurred_at = models.DateTimeField()


    class Meta:
        verbose_name = _('incidents')
        verbose_name_plural = _('incidents')
        unique_together = (("service_key", "incident_key"),)

    def __str__(self):
        return self.incident_key

    def natural_key(self):
        return (self.service_key, self.incident_key)
    def clean(self):
        if self.event_type not in ['trigger', 'acknowledge', 'resolve']:
            raise ValidationError("'%s' is an invalid event type, valid values are 'trigger', 'acknowledge' and 'resolve'" % self.event_type)

@python_2_unicode_compatible
class ServiceTokens(models.Model):
    """
    Service tokens
    """
    name = models.CharField(max_length=80)
    service_id = models.ForeignKey(Service)
    token_id = models.ForeignKey(Token)

    class Meta:
        verbose_name = _('service_tokens')
        verbose_name_plural = _('service_tokens')

    def __str__(self):
        return self.name




@python_2_unicode_compatible
class SchedulePolicyRule(models.Model):
    """
    Schedule rule
    """
    schedule_policy = models.ForeignKey(SchedulePolicy, related_name='rules')
    position = models.IntegerField()
    user_id = models.ForeignKey(User, blank=True, null=True)
    schedule = models.ForeignKey(Calendar, blank=True, null=True)
    escalate_after = models.IntegerField()

    class Meta:
        verbose_name = _('schedule_policy_rule')
        verbose_name_plural = _('schedule_policy_rules')

    def __str__(self):
        return str(self.id)

    @classmethod
    def getRulesForService(cls, service):
        return cls.objects.filter(schedule_policy=service.policy)

class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', related_name='profile')
    phone_number = models.CharField(max_length=50)
    pushover_user_key = models.CharField(max_length=50)
    pushover_app_key = models.CharField(max_length=50)
    slack_room_name = models.CharField(max_length=50)
    prowl_api_key = models.CharField(max_length=50, blank=True)
    prowl_application = models.CharField(max_length=256, blank=True)
    prowl_url= models.CharField(max_length=512, blank=True)

class ServiceSilenced(models.Model):
    service = models.ForeignKey(Service)
    silenced = models.BooleanField(default=False)
    silenced_until = models.DateTimeField()


class IncidentSilenced(models.Model):
    incident = models.ForeignKey(Incident)
    silenced = models.BooleanField(default=False)
    silenced_until = models.DateTimeField()

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

signals.post_save.connect(create_user_profile, sender=User)

signals.post_syncdb.disconnect(
    create_superuser,
    sender=auth_models,
    dispatch_uid='django.contrib.auth.management.create_superuser')

openduty/views.py
__author__ = 'deathowl'

from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from openduty.serializers import UserSerializer, GroupSerializer, SchedulePolicySerializer, SchedulePolicyRuleSerializer
from models import SchedulePolicy, SchedulePolicyRule


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class SchedulePolicyViewSet(viewsets.ModelViewSet):
    queryset = SchedulePolicy.objects.all()
    serializer_class = SchedulePolicySerializer

class SchedulePolicyRuleViewSet(viewsets.ModelViewSet):
    queryset = SchedulePolicyRule.objects.all()
    serializer_class = SchedulePolicyRuleSerializer

openduty/templates/event/edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% load i18n %}

{% block content %}
    <link rel="stylesheet" href="{% static "schedule/css/schedule.css" %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static "schedule/css/jquery-ui.css" %}" type="text/css" media="screen" />
    <script type="text/javascript" src="{% static "schedule/js/jquery.js" %}"></script>
    <script type="text/javascript" src="{% static "schedule/js/jquery-ui.js" %}"></script>
    <script type="text/javascript" src="{% static "schedule/js/jquery.timePicker.js" %}"></script>
    <script type="text/javascript">
    $(function() {
        $("#id_start_0").datepicker({dateFormat: $.datepicker.ATOM});
        $("#id_end_0").datepicker({dateFormat: $.datepicker.ATOM});
        $("#id_start_1").timePicker();
        $("#id_end_1").timePicker();
        var oldTime = $.timePicker("#id_start_1").getTime();
        $("#id_start_1").change(function() {
          if ($("#id_end_1").val()) { // Only update when second input has a value.
          // Calculate duration.
          var duration = ($.timePicker("#id_end_1").getTime() - oldTime);
          var time = $.timePicker("#id_start_1").getTime();
          // Calculate and update the time in the second input.
          $.timePicker("#id_end_1").setTime(new Date(new Date(time.getTime() + duration)));
          oldTime = time;
          }
        });
        // Validate.
        // TODO this should validate date AND time
        $("#id_end_1").change(function() {
          if($.timePicker("#id_start_1").getTime() > $.timePicker(this).getTime()) {
          $(this).addClass("error");
          }
          else {
          $(this).removeClass("error");
          }
        });
    });
    </script>
<b>{% trans "Create or change event. All fields are required." %}</b>
<br/><br/>
 <form action="" method="post">
 {% csrf_token %}
     <table>
       <tbody>
          <tr>
             <th><label for="id_start_0">start:</label></th>
             <td><input id="id_start_0" name="start_0" type="text" class="datepicker" value="{% if data.start_ymd %} {{data.start_ymd}}{% endif %}">
                 <input id="id_start_1" name="start_1" type="text" class="datepicker" value="{% if data.start_hour %} {{data.start_hour}}{% endif %}"></td>
          </tr>
          <tr>
             <th><label for="id_end_0">end:</label></th>
             <td><input id="id_end_0" name="end_0" type="text" value="{% if data.end_ymd %} {{data.end_ymd}}{% endif %}">
                 <input id="id_end_1" name="end_1" type="text" value="{% if data.end_hour %} {{data.end_hour}}{% endif %}"><br>
                 <span class="helptext">The end time must be later than start time.</span></td>
          </tr>
          <tr>
             <th><label for="id_title">On call</label></th>
          <td>
               <select name="oncall">
                {% for user in users %}
                 <option value="{{user.username}}" {% if data.oncall == user.username %} {{"selected"}}{% endif %}>{{user.username}}</option>
                 {% endfor %}
                 </select>
          </td>
          </tr>
             <tr>
             <th><label for="fallback">Fallback</label></th>
          <td>
               <select name="fallback">
                {% for user in users %}
                 <option value="{{user.username}}" {% if data.fallback == user.username %} {{"selected"}}{% endif %}>{{user.username}}</option>
                 {% endfor %}
                 </select>
          </td>

          </tr>
          <tr>
             <th>Recurring</th>
             <td>{{ form.rule }}</td>
          </tr>
          <tr>
             <th><label for="id_description">Description:</label></th>
             <td><textarea cols="40" id="id_description" name="description" rows="10">{% if data.description %} {{data.description}}{% endif %}</textarea></td>
          </tr>
       </tbody>
    </table>
  <br/>
  <input type="submit" value="{% trans "Save" %}">
  <input type="button" value="{% trans "Cancel" %}" onclick="window.location='/schedules/view/{{ calendar.id }}'"/>
  <input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}